const API_BASE = window.TLT_API_BASE || '/api';
document.addEventListener('DOMContentLoaded',()=>{initNavToggle();initFaqAccordion();initFileLabels();initForms();setYear()});
function initNavToggle(){const t=document.querySelector('.nav-toggle'),l=document.querySelector('.nav-links');if(!t||!l)return;t.addEventListener('click',()=>{const o=l.classList.toggle('open');t.setAttribute('aria-expanded',String(o))});l.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{l.classList.remove('open');t.setAttribute('aria-expanded','false')}))}
function initFaqAccordion(){document.querySelectorAll('.faq-item').forEach(i=>{const b=i.querySelector('.faq-q');if(!b)return;b.addEventListener('click',()=>{const o=i.classList.contains('open');i.parentElement.querySelectorAll('.faq-item').forEach(x=>x.classList.remove('open'));if(!o)i.classList.add('open')})})}
function initFileLabels(){document.querySelectorAll(".file-drop input[type='file']").forEach(i=>i.addEventListener('change',()=>{const l=i.parentElement.querySelector('.filename');if(l)l.textContent=i.files.length?Array.from(i.files).map(f=>f.name).join(', '):''}))}
function setYear(){document.querySelectorAll('[data-year]').forEach(e=>e.textContent=new Date().getFullYear())}
function initForms(){document.querySelectorAll('form[data-form]').forEach(f=>f.addEventListener('submit',e=>handleSubmit(e,f)))}
function validateForm(form,data){const groups=[['requestTutor','Subjects','Please select at least one subject.'],['becomeTutor','Subjects Taught','Please select at least one subject you teach.'],['becomeTutor','Academic Levels Taught','Please select at least one academic level.']];for(const[type,field,msg]of groups)if(form.dataset.form===type&&!data.getAll(field).filter(Boolean).length){showStatus(form.querySelector('.form-status'),'error','More information needed',msg);form.querySelector(`input[name="${field}"]`)?.focus();return false}for(const i of form.querySelectorAll('input[type=file]'))for(const f of i.files||[])if(f.size>5*1024*1024){showStatus(form.querySelector('.form-status'),'error','File too large',`${f.name} exceeds the 5MB limit.`);return false}return true}
async function handleSubmit(e,form){e.preventDefault();if(!form.checkValidity()){form.reportValidity();return}const s=form.querySelector('.form-status'),b=form.querySelector('[type=submit]'),original=b?.textContent||'Submit',data=new FormData(form);if(!validateForm(form,data))return;data.append('type',form.dataset.form);if(b){b.disabled=true;b.textContent='Sending…'}hideStatus(s);try{const r=await fetch(`${API_BASE}/submissions`,{method:'POST',headers:{Accept:'application/json'},body:data}),result=await r.json().catch(()=>({}));if(!r.ok)throw Error(result.error||'Submission failed');showStatus(s,'success',form.dataset.successTitle||'Submission received',form.dataset.successBody||"Thank you — your submission has been sent to our team. We'll be in touch shortly.");form.reset();document.querySelectorAll('.file-drop .filename').forEach(x=>x.textContent='');s?.scrollIntoView({behavior:'smooth',block:'center'})}catch(err){showStatus(s,'error','Something went wrong',err.message||'Your submission could not be sent right now. Please try again.')}finally{if(b){b.disabled=false;b.textContent=original}}}
function showStatus(el,type,title,body){if(!el)return;el.classList.remove('success','error');el.classList.add(type,'show');el.innerHTML=`<span class="icon">${type==='success'?'✓':'!'}</span><div><h4>${escapeHtml(title)}</h4><p>${escapeHtml(body)}</p></div>`}function hideStatus(el){el?.classList.remove('show')}function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
