const crypto = require('crypto');
const { IncomingForm } = require('formidable');
const fs = require('fs');
const WINDOW_MS=15*60*1000,MAX_REQUESTS=20,MAX_FILE=5*1024*1024;
const buckets=new Map();
const json=(res,s,d)=>{res.status(s).setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(d))};
const ip=req=>String(req.headers['x-forwarded-for']||req.socket?.remoteAddress||'unknown').split(',')[0].trim();
const limited=k=>{const n=Date.now(),x=buckets.get(k);if(!x||n-x.started>WINDOW_MS){buckets.set(k,{started:n,count:1});return false}x.count++;return x.count>MAX_REQUESTS};
const clean=(v,n=5000)=>Array.isArray(v)?clean(v[0],n):typeof v==='string'?v.trim().slice(0,n):'';
const admin=req=>process.env.ADMIN_API_KEY&&req.headers.authorization===`Bearer ${process.env.ADMIN_API_KEY}`;
function originOK(req){const a=(process.env.ALLOWED_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean);return !a.length||!req.headers.origin||a.includes(req.headers.origin)}
async function supabase(path,opts={}){const b=process.env.SUPABASE_URL,k=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!b||!k)return null;const r=await fetch(`${b.replace(/\/$/,'')}/rest/v1/${path}`,{...opts,headers:{apikey:k,Authorization:`Bearer ${k}`,'Content-Type':'application/json',Prefer:'return=representation',...(opts.headers||{})}});if(!r.ok)throw Error(`Database request failed: ${r.status}`);return r.status===204?null:r.json()}
function parseMultipart(req){return new Promise((resolve,reject)=>{new IncomingForm({maxFileSize:MAX_FILE,maxTotalFileSize:MAX_FILE*2,allowEmptyFiles:false,multiples:true}).parse(req,(e,f,files)=>e?reject(e):resolve({fields:f,files}))})}
async function parse(req){if(String(req.headers['content-type']||'').includes('multipart/form-data'))return parseMultipart(req);let n=0,a=[];for await(const c of req){n+=c.length;if(n>65536)throw Object.assign(Error('Request too large'),{status:413});a.push(c)}try{return{fields:JSON.parse(Buffer.concat(a).toString()||'{}'),files:{}}}catch{throw Object.assign(Error('Invalid JSON'),{status:400})}}
function validate(p){if(!['requestTutor','becomeTutor','contact'].includes(clean(p.type,30)))return'Invalid submission type';if(clean(p.website))return'Spam detected';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(clean(p.email,320)))return'Valid email is required';if(!clean(p.fullName,150))return'Full name is required';if(p.type==='contact'&&!clean(p.message,10000))return'Message is required';if(p.type==='requestTutor'&&!clean(p.learningGoals,10000))return'Learning goals are required';if(p.type==='becomeTutor'&&!p._hasCV)return'CV is required';return null}
async function storeFiles(files,id){const b=process.env.SUPABASE_URL,k=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!b||!k)return[];const bucket=process.env.SUPABASE_STORAGE_BUCKET||'applications',all=Object.values(files).flatMap(v=>Array.isArray(v)?v:[v]).filter(Boolean),out=[];for(const f of all){if(f.size>MAX_FILE)throw Object.assign(Error('A file exceeds the 5MB limit'),{status:413});const name=`${id}/${crypto.randomUUID()}-${String(f.originalFilename||'file').replace(/[^a-zA-Z0-9._-]/g,'_')}`;const r=await fetch(`${b.replace(/\/$/,'')}/storage/v1/object/${bucket}/${name}`,{method:'POST',headers:{Authorization:`Bearer ${k}`,apikey:k,'Content-Type':f.mimetype||'application/octet-stream','x-upsert':'false'},body:fs.createReadStream(f.filepath)});if(!r.ok)throw Error(`File storage failed: ${r.status}`);out.push({name:f.originalFilename,mime:f.mimetype,size:f.size,path:name})}return out}
module.exports=async function(req,res){
 if(req.method==='GET'){if(!admin(req))return json(res,401,{error:'Unauthorized'});try{return json(res,200,await supabase('submissions?select=*&order=created_at.desc')||[])}catch(e){console.error(e);return json(res,500,{error:'Unable to load submissions'})}}
 if(req.method==='PATCH'){if(!admin(req))return json(res,401,{error:'Unauthorized'});try{const {id,status}=await parse(req);if(!/^[0-9a-f-]{36}$/i.test(clean(id,40))||!['new','reviewing','matched','approved','rejected','closed'].includes(clean(status,20)))return json(res,400,{error:'Invalid update'});const rows=await supabase(`submissions?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({status})});return json(res,200,rows?.[0]||{})}catch(e){console.error(e);return json(res,500,{error:'Unable to update submission'})}}
 if(req.method!=='POST')return json(res,405,{error:'Method not allowed'});if(!originOK(req))return json(res,403,{error:'Origin not allowed'});if(limited(ip(req)))return json(res,429,{error:'Too many submissions. Please try again later.'});
 try{const {fields,files}=await parse(req),p=fields,allFiles=Object.values(files).flatMap(v=>Array.isArray(v)?v:[v]).filter(Boolean);p._hasCV=allFiles.some(f=>f.fieldName==='CV');const error=validate(p);if(error)return json(res,400,{error});const id=crypto.randomUUID(),stored=allFiles.length?await storeFiles(files,id):[];const payload=Object.fromEntries(Object.entries(p).filter(([k])=>!['_hasCV','website','type'].includes(k)));payload._files=stored;const row={id,type:p.type,full_name:clean(p.fullName,150),email:clean(p.email,320),phone:clean(payload['Phone Number'],60),payload};const saved=await supabase('submissions',{method:'POST',body:JSON.stringify(row)});if(!saved)return json(res,503,{error:'Database is not configured yet'});return json(res,201,{ok:true,id})}catch(e){console.error(e);return json(res,e.status||500,{error:e.message&&e.message.length<100?e.message:'Unable to process submission'})}
};
